apiVersion: v2
name: confluence
description: A chart for installing Confluence Data Center on Kubernetes
type: application
version: 1.8.0
appVersion: 7.19.4
kubeVersion: ">=1.21.x-0"
keywords:
- Confluence
- Confluence Server
- Confluence Data Center
- Confluence DC
- Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/confluence.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-atlassian-confluence-server/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |-
    - Stop supporting 1.19 and 1.20 k8s
    - Update appVersion to the latest LTS
    - Create Role instead of ClusterRole for Hazelcast Kube client in Confluence and Bitbucket Helm charts
    - Make synchrony pod and service annotations configurable
    - Make Hazelcast port configurable

dependencies:
- name: common
  version: 1.0.0
  repository: https://atlassian.github.io/data-center-helm-charts
