{{- if .Values.ingress.create }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "bitbucket.fullname" . }}
  labels:
    {{- include "bitbucket.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: "/"
            backend:
              serviceName: {{ include "bitbucket.fullname" $ }}
              servicePort: {{ $.Values.bitbucket.service.port }}
{{ end }}