{{- if .Values.ingress.create }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "confluence.fullname" . }}
  labels:
    {{- include "confluence.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: "/"
            backend:
              serviceName: {{ include "confluence.fullname" . }}
              servicePort: {{ $.Values.confluence.service.port }}
          {{ if .Values.synchrony.enabled }}
          - path: "/synchrony"
            backend:
              serviceName: {{ include "synchrony.fullname" . }}
              servicePort: {{ $.Values.synchrony.service.port }}
          {{ end }}
{{ end }}