{{- if .Values.ingress.create }}
{{- include "confluence.ingress" (list . "confluence.regular.ingress") -}}
{{- end -}}
{{- define "confluence.regular.ingress" -}}
metadata:
  name: {{ include "confluence.fullname" . }}-setup
  annotations:
    "nginx.ingress.kubernetes.io/proxy-connect-timeout": "300"
    "nginx.ingress.kubernetes.io/proxy-read-timeout": "300"
    "nginx.ingress.kubernetes.io/proxy-send-timeout": "300"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: "/setup"
            backend:
              serviceName: {{ include "confluence.fullname" . }}
              servicePort: {{ $.Values.confluence.service.port }}
{{- end -}}